/* automatically generated by configure */
/* on Mon Nov 9 17:23:11 UTC 2015 */
/* target uppercase defines */
 
#ifndef TARGET_OS_LINUX_GNUEABIHF
#define TARGET_OS_LINUX_GNUEABIHF "linux-gnueabihf"
#endif
 
#ifndef TARGET_OS_LINUX
#define TARGET_OS_LINUX "linux-gnueabihf"
#endif
 
#ifndef TARGET_OS_TYPE
#define TARGET_OS_TYPE "linux-gnueabihf"
#endif
 
#ifndef TARGET_CPU_ARMV7L
#define TARGET_CPU_ARMV7L "armv7l"
#endif
 
#ifndef TARGET_CPU_ARMV
#define TARGET_CPU_ARMV "armv7l"
#endif
 
#ifndef TARGET_CPU_TYPE
#define TARGET_CPU_TYPE "armv7l"
#endif
 
#ifndef TARGET_ARCH_ARM
#define TARGET_ARCH_ARM "arm"
#endif
 
#ifndef TARGET_ARCH_TYPE
#define TARGET_ARCH_TYPE "arm"
#endif
/* host uppercase defines */
 
#ifndef HOST_OS_LINUX_GNUEABIHF
#define HOST_OS_LINUX_GNUEABIHF "linux-gnueabihf"
#endif
 
#ifndef HOST_OS_LINUX
#define HOST_OS_LINUX "linux-gnueabihf"
#endif
 
#ifndef HOST_OS_TYPE
#define HOST_OS_TYPE "linux-gnueabihf"
#endif
 
#ifndef HOST_CPU_ARMV7L
#define HOST_CPU_ARMV7L "armv7l"
#endif
 
#ifndef HOST_CPU_ARMV
#define HOST_CPU_ARMV "armv7l"
#endif
 
#ifndef HOST_CPU_TYPE
#define HOST_CPU_TYPE "armv7l"
#endif
 
#ifndef HOST_ARCH_ARM
#define HOST_ARCH_ARM "arm"
#endif
 
#ifndef HOST_ARCH_TYPE
#define HOST_ARCH_TYPE "arm"
#endif
